### ISSUE TITLE
use DEFAULT instead complex merging stategy

### ISSUE THREAD

**Issue by esler** [peoplepath/phpunit-db-fixtures#13]
let's say you have data like this
```yaml
user:
- 
  name: Alice
  title: MBA
 -
  name: Bob
```
today we somehow guess default value of {{Bob}} and insert it into DB like this (for example)
```sql
INSERT INTO `user` () VALUES ('Alice','MBA'),('Bob','');
```
my proposal is to omit guessing and let DB to do it
```sql
INSERT INTO `user` () VALUES ('Alice','MBA'),('Bob',DEFAULT);
```
